version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn -X -f amazon-kinesis-data-analytics-flink-starter-kit-master/pom.xml clean install
      - mvn -q --batch-mode --update-snapshots -f aws-kms-pq-tls-example-main/pom.xml package
      - mvn -q --batch-mode --update-snapshots -f skiresort-example-dynamodb-aws-sdk-v1-main/pom.xml package
      - mvn -q --batch-mode --update-snapshots -f rds-breakglass-user-management-master/pom.xml package
      - mvn -q -f exporting-tool-for-amazon-keyspaces-main/pom.xml install package
