name: build-med

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
              mvn -X -f amazon-kinesis-data-analytics-flink-starter-kit-master/pom.xml clean install
              mvn -q --batch-mode --update-snapshots -f aws-kms-pq-tls-example-main/pom.xml package
              mvn -q --batch-mode --update-snapshots -f skiresort-example-dynamodb-aws-sdk-v1-main/pom.xml package
              mvn -q --batch-mode --update-snapshots -f rds-breakglass-user-management-master/pom.xml package
              mvn -q -f exporting-tool-for-amazon-keyspaces-main/pom.xml install package
